services:
  postgres:
    image: postgres:15
    container_name: nest_graphql_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-nestgraphql}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_graphql_api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DATABASE_USER:-postgres}
      DB_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      DB_NAME: ${DATABASE_NAME:-nestgraphql}
      STAGE: ${STAGE:-dev}
volumes:
  postgres_data:
